name: pr-workflow
run-name: ${{ github.event_name }}  ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
#  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main
      - 'releases/**'
  workflow_dispatch:
#defaults:
#  run:
#    shell: bash |pwsh
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: installing .net sdk
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
      
      - name: Restore dependencies
        run: dotnet restore ./github_action_study.sln
      
      - name: Build
        run: dotnet build ./github_action_study.sln --no-restore --configuration Release
      
      - name: Test
        run: dotnet test ./github_action_study.sln --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"
        
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: .Net Tests
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx       
  
  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./bootstrapper/bootstrapper.csproj

      - name: Publish
        run: dotnet publish ./bootstrapper/bootstrapper.csproj --configuration Release --output ./publish_output
 
      - name: Get Event Details
        run: echo "EVENT_NAME=${{ toJSON(github.event_name) }}" >> $GITHUB_ENV
        
      - name: Deploy to Target Environment
        uses: actions/upload-artifact@v4
        with:
          path: './publish_output'